# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from faultlab.proto import dkg_pb2 as faultlab_dot_proto_dot_dkg__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in faultlab/proto/dkg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DkgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitDkg = channel.unary_unary(
                '/mpc.signer.DkgService/InitDkg',
                request_serializer=faultlab_dot_proto_dot_dkg__pb2.InitDkgRequest.SerializeToString,
                response_deserializer=faultlab_dot_proto_dot_dkg__pb2.InitDkgResponse.FromString,
                _registered_method=True)
        self.AdvanceDkg = channel.unary_unary(
                '/mpc.signer.DkgService/AdvanceDkg',
                request_serializer=faultlab_dot_proto_dot_dkg__pb2.AdvanceDkgRequest.SerializeToString,
                response_deserializer=faultlab_dot_proto_dot_dkg__pb2.AdvanceDkgResponse.FromString,
                _registered_method=True)


class DkgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitDkg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvanceDkg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DkgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitDkg': grpc.unary_unary_rpc_method_handler(
                    servicer.InitDkg,
                    request_deserializer=faultlab_dot_proto_dot_dkg__pb2.InitDkgRequest.FromString,
                    response_serializer=faultlab_dot_proto_dot_dkg__pb2.InitDkgResponse.SerializeToString,
            ),
            'AdvanceDkg': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvanceDkg,
                    request_deserializer=faultlab_dot_proto_dot_dkg__pb2.AdvanceDkgRequest.FromString,
                    response_serializer=faultlab_dot_proto_dot_dkg__pb2.AdvanceDkgResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mpc.signer.DkgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mpc.signer.DkgService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DkgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitDkg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpc.signer.DkgService/InitDkg',
            faultlab_dot_proto_dot_dkg__pb2.InitDkgRequest.SerializeToString,
            faultlab_dot_proto_dot_dkg__pb2.InitDkgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvanceDkg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpc.signer.DkgService/AdvanceDkg',
            faultlab_dot_proto_dot_dkg__pb2.AdvanceDkgRequest.SerializeToString,
            faultlab_dot_proto_dot_dkg__pb2.AdvanceDkgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
