# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: faultlab/proto/dkg.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'faultlab/proto/dkg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x66\x61ultlab/proto/dkg.proto\x12\nmpc.signer\"y\n\x0eInitDkgRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08party_id\x18\x02 \x01(\r\x12\x11\n\tthreshold\x18\x03 \x01(\r\x12\x15\n\rtotal_parties\x18\x04 \x01(\r\x12\x17\n\x0f\x64\x65rivation_path\x18\x05 \x01(\t\"\"\n\x0fInitDkgResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"K\n\x11\x41\x64vanceDkgRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08party_id\x18\x02 \x01(\r\x12\x10\n\x08payloads\x18\x03 \x03(\x0c\"5\n\x12\x41\x64vanceDkgResponse\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x12\x0f\n\x07is_done\x18\x02 \x01(\x08\x32\x9d\x01\n\nDkgService\x12\x42\n\x07InitDkg\x12\x1a.mpc.signer.InitDkgRequest\x1a\x1b.mpc.signer.InitDkgResponse\x12K\n\nAdvanceDkg\x12\x1d.mpc.signer.AdvanceDkgRequest\x1a\x1e.mpc.signer.AdvanceDkgResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faultlab.proto.dkg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITDKGREQUEST']._serialized_start=40
  _globals['_INITDKGREQUEST']._serialized_end=161
  _globals['_INITDKGRESPONSE']._serialized_start=163
  _globals['_INITDKGRESPONSE']._serialized_end=197
  _globals['_ADVANCEDKGREQUEST']._serialized_start=199
  _globals['_ADVANCEDKGREQUEST']._serialized_end=274
  _globals['_ADVANCEDKGRESPONSE']._serialized_start=276
  _globals['_ADVANCEDKGRESPONSE']._serialized_end=329
  _globals['_DKGSERVICE']._serialized_start=332
  _globals['_DKGSERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
