"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class InitDkgRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    PARTY_ID_FIELD_NUMBER: _builtins.int
    THRESHOLD_FIELD_NUMBER: _builtins.int
    TOTAL_PARTIES_FIELD_NUMBER: _builtins.int
    DERIVATION_PATH_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    party_id: _builtins.int
    threshold: _builtins.int
    total_parties: _builtins.int
    derivation_path: _builtins.str
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        party_id: _builtins.int = ...,
        threshold: _builtins.int = ...,
        total_parties: _builtins.int = ...,
        derivation_path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["derivation_path", b"derivation_path", "party_id", b"party_id", "session_id", b"session_id", "threshold", b"threshold", "total_parties", b"total_parties"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InitDkgRequest: _TypeAlias = InitDkgRequest  # noqa: Y015

@_typing.final
class InitDkgResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InitDkgResponse: _TypeAlias = InitDkgResponse  # noqa: Y015

@_typing.final
class AdvanceDkgRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    PARTY_ID_FIELD_NUMBER: _builtins.int
    PAYLOADS_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    party_id: _builtins.int
    @_builtins.property
    def payloads(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        party_id: _builtins.int = ...,
        payloads: _abc.Iterable[_builtins.bytes] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["party_id", b"party_id", "payloads", b"payloads", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AdvanceDkgRequest: _TypeAlias = AdvanceDkgRequest  # noqa: Y015

@_typing.final
class AdvanceDkgResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OUTPUT_FIELD_NUMBER: _builtins.int
    IS_DONE_FIELD_NUMBER: _builtins.int
    output: _builtins.bytes
    is_done: _builtins.bool
    def __init__(
        self,
        *,
        output: _builtins.bytes = ...,
        is_done: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_done", b"is_done", "output", b"output"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AdvanceDkgResponse: _TypeAlias = AdvanceDkgResponse  # noqa: Y015
