"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from faultlab.proto import dkg_pb2 as _dkg_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DkgServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DkgServiceAsyncStub: ...
    InitDkg: _grpc.UnaryUnaryMultiCallable[_dkg_pb2.InitDkgRequest, _dkg_pb2.InitDkgResponse]
    AdvanceDkg: _grpc.UnaryUnaryMultiCallable[_dkg_pb2.AdvanceDkgRequest, _dkg_pb2.AdvanceDkgResponse]

@_typing.type_check_only
class DkgServiceAsyncStub(DkgServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    InitDkg: _aio.UnaryUnaryMultiCallable[_dkg_pb2.InitDkgRequest, _dkg_pb2.InitDkgResponse]  # type: ignore[assignment]
    AdvanceDkg: _aio.UnaryUnaryMultiCallable[_dkg_pb2.AdvanceDkgRequest, _dkg_pb2.AdvanceDkgResponse]  # type: ignore[assignment]

class DkgServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def InitDkg(
        self,
        request: _dkg_pb2.InitDkgRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_dkg_pb2.InitDkgResponse, _abc.Awaitable[_dkg_pb2.InitDkgResponse]]: ...

    @_abc_1.abstractmethod
    def AdvanceDkg(
        self,
        request: _dkg_pb2.AdvanceDkgRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_dkg_pb2.AdvanceDkgResponse, _abc.Awaitable[_dkg_pb2.AdvanceDkgResponse]]: ...

def add_DkgServiceServicer_to_server(servicer: DkgServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
