# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/dsg.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/dsg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/dsg.proto\x12\nmpc.signer\"y\n\x0eInitDsgRequest\x12\x0e\n\x06key_id\x18\x01 \x01(\t\x12\x16\n\x0e\x64sg_session_id\x18\x02 \x01(\t\x12\x10\n\x08party_id\x18\x03 \x01(\r\x12\x14\n\x0cmessage_hash\x18\x04 \x01(\x0c\x12\x17\n\x0f\x64\x65rivation_path\x18\x05 \x01(\t\"\"\n\x0fInitDsgResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"O\n\x11\x41\x64vanceDsgRequest\x12\x16\n\x0e\x64sg_session_id\x18\x01 \x01(\t\x12\x10\n\x08party_id\x18\x02 \x01(\r\x12\x10\n\x08payloads\x18\x03 \x03(\x0c\"5\n\x12\x41\x64vanceDsgResponse\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x12\x0f\n\x07is_done\x18\x02 \x01(\x08\x32\x9d\x01\n\nDsgService\x12\x42\n\x07InitDsg\x12\x1a.mpc.signer.InitDsgRequest\x1a\x1b.mpc.signer.InitDsgResponse\x12K\n\nAdvanceDsg\x12\x1d.mpc.signer.AdvanceDsgRequest\x1a\x1e.mpc.signer.AdvanceDsgResponseB&\n$uk.ac.herts.orchestrator.grpc.signerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.dsg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$uk.ac.herts.orchestrator.grpc.signer'
  _globals['_INITDSGREQUEST']._serialized_start=31
  _globals['_INITDSGREQUEST']._serialized_end=152
  _globals['_INITDSGRESPONSE']._serialized_start=154
  _globals['_INITDSGRESPONSE']._serialized_end=188
  _globals['_ADVANCEDSGREQUEST']._serialized_start=190
  _globals['_ADVANCEDSGREQUEST']._serialized_end=269
  _globals['_ADVANCEDSGRESPONSE']._serialized_start=271
  _globals['_ADVANCEDSGRESPONSE']._serialized_end=324
  _globals['_DSGSERVICE']._serialized_start=327
  _globals['_DSGSERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
