# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import dsg_pb2 as proto_dot_dsg__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/dsg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DsgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitDsg = channel.unary_unary(
                '/mpc.signer.DsgService/InitDsg',
                request_serializer=proto_dot_dsg__pb2.InitDsgRequest.SerializeToString,
                response_deserializer=proto_dot_dsg__pb2.InitDsgResponse.FromString,
                _registered_method=True)
        self.AdvanceDsg = channel.unary_unary(
                '/mpc.signer.DsgService/AdvanceDsg',
                request_serializer=proto_dot_dsg__pb2.AdvanceDsgRequest.SerializeToString,
                response_deserializer=proto_dot_dsg__pb2.AdvanceDsgResponse.FromString,
                _registered_method=True)


class DsgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitDsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvanceDsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DsgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitDsg': grpc.unary_unary_rpc_method_handler(
                    servicer.InitDsg,
                    request_deserializer=proto_dot_dsg__pb2.InitDsgRequest.FromString,
                    response_serializer=proto_dot_dsg__pb2.InitDsgResponse.SerializeToString,
            ),
            'AdvanceDsg': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvanceDsg,
                    request_deserializer=proto_dot_dsg__pb2.AdvanceDsgRequest.FromString,
                    response_serializer=proto_dot_dsg__pb2.AdvanceDsgResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mpc.signer.DsgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mpc.signer.DsgService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DsgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitDsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpc.signer.DsgService/InitDsg',
            proto_dot_dsg__pb2.InitDsgRequest.SerializeToString,
            proto_dot_dsg__pb2.InitDsgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvanceDsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpc.signer.DsgService/AdvanceDsg',
            proto_dot_dsg__pb2.AdvanceDsgRequest.SerializeToString,
            proto_dot_dsg__pb2.AdvanceDsgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
