"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from proto import dsg_pb2 as _dsg_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DsgServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DsgServiceAsyncStub: ...
    ExecuteDsgPhase: _grpc.UnaryUnaryMultiCallable[_dsg_pb2.DsgPhaseRequest, _dsg_pb2.DsgPhaseResponse]

@_typing.type_check_only
class DsgServiceAsyncStub(DsgServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    ExecuteDsgPhase: _aio.UnaryUnaryMultiCallable[_dsg_pb2.DsgPhaseRequest, _dsg_pb2.DsgPhaseResponse]  # type: ignore[assignment]

class DsgServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def ExecuteDsgPhase(
        self,
        request: _dsg_pb2.DsgPhaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_dsg_pb2.DsgPhaseResponse, _abc.Awaitable[_dsg_pb2.DsgPhaseResponse]]: ...

def add_DsgServiceServicer_to_server(servicer: DsgServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
