"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DsgPhaseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DSG_SESSION_ID_FIELD_NUMBER: _builtins.int
    PARTY_ID_FIELD_NUMBER: _builtins.int
    INIT_FIELD_NUMBER: _builtins.int
    PEER_PAYLOADS_FIELD_NUMBER: _builtins.int
    dsg_session_id: _builtins.str
    party_id: _builtins.int
    @_builtins.property
    def init(self) -> Global___InitPayload: ...
    @_builtins.property
    def peer_payloads(self) -> Global___PeerPayloads: ...
    def __init__(
        self,
        *,
        dsg_session_id: _builtins.str = ...,
        party_id: _builtins.int = ...,
        init: Global___InitPayload | None = ...,
        peer_payloads: Global___PeerPayloads | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["init", b"init", "payload", b"payload", "peer_payloads", b"peer_payloads"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dsg_session_id", b"dsg_session_id", "init", b"init", "party_id", b"party_id", "payload", b"payload", "peer_payloads", b"peer_payloads"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["init", "peer_payloads"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___DsgPhaseRequest: _TypeAlias = DsgPhaseRequest  # noqa: Y015

@_typing.final
class InitPayload(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_ID_FIELD_NUMBER: _builtins.int
    MESSAGE_HASH_FIELD_NUMBER: _builtins.int
    DERIVATION_PATH_FIELD_NUMBER: _builtins.int
    key_id: _builtins.str
    message_hash: _builtins.bytes
    derivation_path: _builtins.str
    def __init__(
        self,
        *,
        key_id: _builtins.str = ...,
        message_hash: _builtins.bytes = ...,
        derivation_path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["derivation_path", b"derivation_path", "key_id", b"key_id", "message_hash", b"message_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InitPayload: _TypeAlias = InitPayload  # noqa: Y015

@_typing.final
class PeerPayloads(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAYLOADS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def payloads(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        payloads: _abc.Iterable[_builtins.bytes] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payloads", b"payloads"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PeerPayloads: _TypeAlias = PeerPayloads  # noqa: Y015

@_typing.final
class SignatureShare(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    S_0_FIELD_NUMBER: _builtins.int
    S_1_FIELD_NUMBER: _builtins.int
    R_FIELD_NUMBER: _builtins.int
    s_0: _builtins.bytes
    s_1: _builtins.bytes
    r: _builtins.bytes
    def __init__(
        self,
        *,
        s_0: _builtins.bytes = ...,
        s_1: _builtins.bytes = ...,
        r: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["r", b"r", "s_0", b"s_0", "s_1", b"s_1"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SignatureShare: _TypeAlias = SignatureShare  # noqa: Y015

@_typing.final
class DsgPhaseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INTERMEDIATE_OUTPUT_FIELD_NUMBER: _builtins.int
    SIGNATURE_SHARE_FIELD_NUMBER: _builtins.int
    intermediate_output: _builtins.bytes
    @_builtins.property
    def signature_share(self) -> Global___SignatureShare: ...
    def __init__(
        self,
        *,
        intermediate_output: _builtins.bytes = ...,
        signature_share: Global___SignatureShare | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["intermediate_output", b"intermediate_output", "result", b"result", "signature_share", b"signature_share"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["intermediate_output", b"intermediate_output", "result", b"result", "signature_share", b"signature_share"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["intermediate_output", "signature_share"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___DsgPhaseResponse: _TypeAlias = DsgPhaseResponse  # noqa: Y015
