spring:
  application:
    name: blockchain-orchestrator
  main:
    web-application-type: servlet

  # DB
  datasource:
    username: ${DB_USERNAME:kapellmeister}
    password: ${DB_PASSWORD:bach}
    jdbcUrl: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/orchestrator}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  # Hardhat
  hardhat:
    rpc-url: ${HARDHAT_RPC_URL:http://127.0.0.1:8545}
    max-retries: ${HARDHAT_MAX_RETRIES:3}
    gas-limit: ${HARDHAT_GAS_LIMIT:21000}
    request-timeout: ${HARDHAT_REQUEST_TIMEOUT:10s}
    retry-backoff: ${HARDHAT_RETRY_BACKOFF:300ms}
    receipt-poll-interval: ${HARDHAT_RECEIPT_POLL_INTERVAL:1s}

  mpc:
    signer-addresses: ${SIGNER_RPC_URLS:127.0.0.1:50051,127.0.0.1:50051,127.0.0.1:50051}
    dsg:
      max-retries: ${DSG_MAX_ATTEMPTS:3}
      request-timeout: ${DSG_REQUEST_TIMEOUT:10s}
      eth-derivation-path: ${DSG_ETH_DERIVATION_PATH:m/0}

logging:
  level:
    root: INFO
    uk.ac.herts.orchestrator: DEBUG
    uk.ac.herts.orchestrator.config: DEBUG
    uk.ac.herts.orchestrator.util: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%-5level] [trace_id=%X{traceId}] %logger{36} - %msg%n"