spring:
  application:
    name: blockchain-orchestrator
  main:
    web-application-type: servlet

  # DB
  datasource:
    username: ${DB_USERNAME:kapellmeister}
    password: ${DB_PASSWORD:bach}
    jdbcUrl: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/orchestrator}
    driver-class-name: org.postgresql.Driver
    sql:
      init:
        mode: ${DB_INIT_MODE:always}
        schema-locations: ${DB_SCHEMA_LOCATION:classpath:schema.sql}
        data-locations: ${DB_DATA_LOCATION:classpath:data.sql}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Hardhat
  hardhat:
    rpc-url: ${HARDHAT_RPC_URL:http://127.0.0.1:8545}
    private-key: ${HARDHAT_PRIVATE_KEY:0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
    transaction-timeout: ${HARDHAT_TX_TIMEOUT:20s}
    max-retries: ${HARDHAT_MAX_RETRIES:3}
    retry-backoff: ${HARDHAT_RETRY_BACKOFF:300ms}
    receipt-poll-interval: ${HARDHAT_RECEIPT_POLL_INTERVAL:1s}
    gas-limit: ${HARDHAT_GAS_LIMIT:21000}
    chain-id: ${HARDHAT_CHAIN_ID:}
    recovery-concurrency: ${HARDHAT_RECOVERY_CONCURRENCY:4}
    recovery-interval-ms: ${HARDHAT_RECOVERY_INTERVAL_MS:30000}

  ssl:
    bundle:
      jks:
        sslclient:
          truststore:
            location: ${SSL_TRUSTSTORE_LOCATION:classpath:certs/ca.p12}
            password: ${SSL_TRUSTSTORE_PASS:secret}

  mpc:
    signer-addresses: ${SIGNER_RPC_URLS:127.0.0.1:50051,127.0.0.1:50051,127.0.0.1:50051}

  # grpc:
  #   client:
  #     channels:
  #       signer:
  #         ssl:
  #           bundle: sslclient
  #         address: ${SIGNER_RPC_URL:127.0.0.1:8081}
  #         negotiation-type: TLS

logging:
  level:
    root: INFO
    uk.ac.herts.orchestrator: DEBUG
    uk.ac.herts.orchestrator.config: DEBUG
    uk.ac.herts.orchestrator.util: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"